"""empty message

Revision ID: 07ef365b4d9c
Revises: 85084f005aac
Create Date: 2021-05-25 11:46:52.438468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ef365b4d9c'
down_revision = '85084f005aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
