"""create users, products, order, and wishlist table

Revision ID: 4d36b0c44026
Revises: ffdc0a98111c
Create Date: 2021-05-24 15:47:47.847821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d36b0c44026'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('cc_card_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('fname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('lname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    op.drop_column('users', 'cc_card_number')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
